export const GET_REPORTS = "GET_REPORTS";
export const GET_STATION_INFO = "GET_STATION_INFO";
export const REPORT_INPUT_UPDATE = "REPORT_INPUT_UPDATE";
export const STATION_INFO_INPUT_UPDATE = "STATION_INFO_INPUT_UPDATE";
